gitSourceBranch = "main"

[home]
enabled = true
includeReadme = false

[docusaurus]
organizationName = "Minstrix"
tagline = "A collection of utilities for Roblox Developers"
favicon = "/favicon.ico"

[[classOrder]]
section = "Tables"
classes = ["Table", "Array"]

[footer]
copyright = "Made with ❤️ by Minstrix"
