name: Publish docs to GitHub Pages
on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Create Node Environment
              uses: actions/setup-node@v2
              with:
                  node-version: "14"
            - name: Install Moonwave
              run: npm i -g moonwave@0.3.4
            - name: Publish Docs
              run: |
                  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  git config --global user.email "support+actions@github.com"
                  git config --global user.name "github-actions-bot"
                  moonwave build --publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
